exp: fm
eval: True
id: single_mod
data: CITYSCAPES_RGB
data_folder: data
batch_size: 16
future_frames: 28  # Future frames to predict

ae_config: configs/vae/8x128x128.yaml
ae_model: checkpoints/ae_rgb_8f_cityscapes.pth
ae_cond_config: configs/vae/2x128x128.yaml
ae_cond_model: checkpoints/ae_rgb_2f_cityscapes.pth

fm_config: configs/flowmatching/128x128.yaml
fm_model: results/fm_single_mod_CITYSCAPES_RGB_42/ema_model_0.pth # e.g.
